ArmaLife/Framework

- Altis_Life.Altis/Config_Master.hpp
- Altis_Life.Altis/core/shops/fn_clothingMenu.sqf
#8 This adds in two settings into the config master to allow the black box
to be turned on and off plus for the clothing shop to randomly be
placed. @Heavybob Check this out.
> Clothing Preview - Dynamic Positions

- Altis_Life.Altis/core/shops/fn_clothingMenu.sqf
- Altis_Life.Altis/description.ext
- Altis_Life.Altis/dialog/admin_menu.hpp
- Altis_Life.Altis/dialog/bank.hpp
- Altis_Life.Altis/dialog/cell_phone.hpp
- Altis_Life.Altis/dialog/chop_shop.h
- Altis_Life.Altis/dialog/clothing.hpp
- Altis_Life.Altis/dialog/compensate.hpp
- Altis_Life.Altis/dialog/deathScreen.h
- Altis_Life.Altis/dialog/federalReserve.h
- Altis_Life.Altis/dialog/gang.hpp
- Altis_Life.Altis/dialog/impound.hpp
- Altis_Life.Altis/dialog/key_chain.hpp
- Altis_Life.Altis/dialog/pInteraction.h
- Altis_Life.Altis/dialog/player_inv.hpp
- Altis_Life.Altis/dialog/settings.h
- Altis_Life.Altis/dialog/shop_items.hpp
- Altis_Life.Altis/dialog/shops.hpp
- Altis_Life.Altis/dialog/spawnSelection.hpp
- Altis_Life.Altis/dialog/ticket.hpp
- Altis_Life.Altis/dialog/trunk.hpp
- Altis_Life.Altis/dialog/ui.hpp
- Altis_Life.Altis/dialog/veh_shop.hpp
- Altis_Life.Altis/dialog/vehicleShop.h
- Altis_Life.Altis/dialog/wanted_list.hpp
There's still something wrong with some of the variables (e.g. _ut3 and _x at some point).
> Fix too many brackets in fn_clothingMenu.sqf & fix for possible makepbo errors

- Altis_Life.Altis/Config_Weapons.hpp
- Altis_Life.Altis/Config_vItems.hpp
- Altis_Life.Altis/mission.sqm
- Altis_Life.Altis/stringtable.xml
Here is a new shop - fuel station - 23 pices / desk+nikos
> Fuel station shops and coffe

- Altis_Life.Altis/Config_Weapons.hpp
Wrong classname for the mag...
> Fix the 7.62 Rahim Mag

- Altis_Life.Altis/Config_Master.hpp
- Altis_Life.Altis/core/shops/fn_clothingMenu.sqf
This includes the dynamic positioning for clothing shops. @Heavybob Can you test this a final time.
> Clothing Preview - Dynamic Position

- Altis_Life.Altis/Config_Master.hpp
- Altis_Life.Altis/core/fn_initMedic.sqf
Ability to either allow or disallow medic firearms.
> Disallow medics firearms

- Altis_Life.Altis/core/pmenu/fn_p_openMenu.sqf
Prevent player menu access whilst restrained
> Prevent Pmenu

- Altis_Life.Altis/core/functions/fn_inventoryOpened.sqf
- Altis_Life.Altis/core/functions/fn_keyHandler.sqf
@Heavybob, can you test it for me? (Needs more than one player)
It should:
Allow owner to open vehicle trunk, vehicle inventory (arma inv.) and house containers without unlocking it.
Also, it should fix lock for house containers and vehicle inv. if players isn't a owner.
> Containers locked fix

- Altis_Life.Altis/core/functions/fn_keyHandler.sqf
Added to KeyHandler as well, should've handled here first...
> Y Menu While Restrained

- life_server/functions.sqf
Map markers & message with coords.
Regarding: https://github.com/ArmaLife/Altis/issues/38
> Add TO - Admin/Cop/EMS Message Markers

- Altis_Life.Altis/Config_Master.hpp
Fixed Helms for Karts to count as masks.
> Masks - Missing Kart Helms

- life_server/functions.sqf
> Server: Functions: Clean message script.

- Altis_Life.Altis/core/admin/fn_admininfo.sqf
- life_server/functions.sqf
A few things that will potentially help those without 3rd party programs to admin their server.
> Admin Menu - Slight Improvements

- Altis_Life.Altis/Config_Master.hpp
- Altis_Life.Altis/core/functions/fn_actionKeyHandler.sqf
- Altis_Life.Altis/core/medical/fn_respawned.sqf
Stops the bodies from laying around or just sinking in the ground. Mentioned in Gitter by someone.
> Body Sink Fix & Enable/Disable ATMs

- Altis_Life.Altis/core/vehicle/fn_vInteractionMenu.sqf
- Altis_Life.Altis/stringtable.xml
add Helicopter interaction and add restriction if the player has the
dlc, the action does not appear
> Heli and Kart Interact

- Altis_Life.Altis/core/functions/network/fn_corpse.sqf
- Altis_Life.Altis/core/medical/fn_revived.sqf
This fixees: https://github.com/ArmaLife/Altis/issues/84
For me at least. May wanna try on some others. Had no issues with medic reviving. Tested as a dead cop getting revived.
> hide -> deleteVehicle

- Altis_Life.Altis/core/actions/fn_catchFish.sqf
- Altis_Life.Altis/core/actions/fn_dropFishingNet.sqf
Fixes: https://github.com/ArmaLife/Altis/issues/119
> Fix classnames

- Altis_Life.Altis/core/init.sqf
People can't seriously like your guy yelling "regroup" every 5 seconds right?
@danielstuart14  can add enableRadio false;  if you wanna disable the commands in chat too if you want. Haven't tested  "enableRadio false;" though.
> Disable Chatter

- Altis_Life.Altis/core/pmenu/fn_p_openMenu.sqf
Assuming this was a mistake at some point.
> Remove Duplicate

- Altis_Life.Altis/core/civilian/fn_removeLicenses.sqf
We use trucking everywhere else ^_^
> truck -> trucking

- Altis_Life.Altis/core/functions/fn_handleItem.sqf
Modify handle items for issue "Clothing Shop Exploit #36"
> Fix HandleItem

- Altis_Life.Altis/Functions.hpp
- Altis_Life.Altis/core/actions/fn_surrender.sqf
- Altis_Life.Altis/core/functions/fn_keyHandler.sqf
https://github.com/ArmaLife/Altis/commit/4eb14b6924a6f9264dcf8ab19d1f41554fea8de0
> Surrender Action

- Altis_Life.Altis/Functions.hpp
- Altis_Life.Altis/core/actions/fn_gutAnimal.sqf
- Altis_Life.Altis/core/functions/fn_actionKeyHandler.sqf
- Altis_Life.Altis/core/functions/fn_nearestObjects.sqf
- life_server/Functions/Systems/fn_huntingZone.sqf
Add gut animal with nearest functions, you need to cursor anything for
pickup the dead animal.
reply of issue Cannot Gut Animals #133
> Gut Animal with nearestobjects

- Altis_Life.Altis/core/medical/fn_revivePlayer.sqf
- Altis_Life.Altis/core/medical/fn_revived.sqf
Should fix: https://github.com/ArmaLife/Altis/issues/140
> Revive Fee Fixes

- Altis_Life.Altis/Config_vItems.hpp
- Altis_Life.Altis/stringtable.xml
Raw meats for the land animals have been added to the market so they can actually be sold (and also bought if you do not wish to hunt and gut them.)
Also edited stringtable.xml - see note for that commit. 
EDIT: Should also fix duplicate mackerel appearing in the shop's inventory.
> Raw meats added to market, misc fixes

- Altis_Life.Altis/Config_Clothing.hpp
Hopefully this fixes my mistake.
> Missing Backpacks

- Altis_Life.Altis/core/items/fn_storageBoxSmall.sqf
- life_server/Functions/Housing/fn_initHouses.sqf
Comma in private removed and file name corrected
> Housing Adjustments

- Altis_Life.Altis/core/housing/fn_containerMenu.sqf
Need it for the CONTROL macros...
> Macro Include

- Altis_Life.Altis/core/functions/fn_actionKeyHandler.sqf
- Altis_Life.Altis/core/medical/fn_onPlayerKilled.sqf
Should disallow revive without request. Tested and works.
> Revive Bug Fix

- Altis_Life.Altis/core/cop/fn_restrain.sqf
Currently if the cop who restrained you dies, you become insta unrestrained. This fixes that, as you already become unrestrained after 5 minutes anyways.
> Dead Cop = Unrestrain Fix

- Altis_Life.Altis/mission.sqm
Ordered the slots so they go from cop_1 -> cop_19.
Since "Bomb Squad" has zero purpose and it's not being used currently,
changed those two to just be name cop too.
> Organize Cop Selections & Descriptions

- Altis_Life.Altis/Config_Master.hpp
> Remove CfgInteractionModels

- Altis_Life.Altis/mission.sqm
- Altis_Life.Altis/stringtable.xml
Added:
- ATM for Police at Pyrgos Station and Highway Patrol Outpost.
- Cop uniform texture for Police NPCs.
Changed:
- Tweaked drug field markers to match the gather radius.
- Tweaks to resource icons. (Required changes to stringtable.xml)
- Miscellaneous changes. 
Removed:
- Pointless "test" marker.
> Some changes to mission.sqm

- Altis_Life.Altis/Functions.hpp
- Altis_Life.Altis/core/civilian/fn_civMarkers.sqf
- Altis_Life.Altis/core/functions/fn_keyHandler.sqf
Markers for civilian group members.
> Civilian Group Markers

- Altis_Life.Altis/core/items/fn_pickaxeUse.sqf
- Altis_Life.Altis/mission.sqm
- Fix not being able to mine at certain resource mines. (issue #206)
- Cleanup for names.
_AKA, fix for issue I introduced in a previous pull. :( Shhh._
> Fix for not being able to mine

- Altis_Life.Altis/core/vehicle/fn_deviceMine.sqf
Same fixes as pull #208 but for the Tempest (Device)/fn_deviceMine.sqf.
> Fix for not being able to mine [using the Tempest (Device)]

- Altis_Life.Altis/core/actions/fn_processAction.sqf
- Altis_Life.Altis/script_macros.hpp
- Altis_Life.Altis/stringtable.xml
- life_server/Functions/Housing/fn_initHouses.sqf
You need to put that on init of NPC for use process : this
enableSimulation false;  this allowDamage false;  this
addAction[localize"STR_Process_Oil",life_fnc_processAction,"ExempleMultiProcess",0,false,false,"",'
!life_is_processing'];
Don't need to modify the line in NPC already place it's work with update.
You have an exemple of multi process in the case for exemple.
> Add multi process

- BEFilters/README.md
In depth notes on how to quickly solve the (BattlEye: Script Restriction#1) bug.
> Script Restriction #1 Notes.

- BEFilters/scripts.txt
Its a bout time I put this in.
> Bossmode Check

- Altis_Life.Altis/core/functions/fn_saveGear.sqf
- Altis_Life.Altis/core/pmenu/fn_useItem.sqf
Turtle Soup is now usable/edible. 
EDIT: Turtle Soup now saves in players' virtual inventories.
> Turtle Soup fixes

- AltisLife.sql
Looking at you @danielstuart14 - https://github.com/ArmaLife/Altis/commit/21720ce7646036cda6be15259f522af47de19826
> AltisLife.sql: Typo fix

- Altis_Life.Altis/Config_Master.hpp
- Altis_Life.Altis/core/actions/fn_serviceChopper.sqf
- Altis_Life.Altis/core/shops/fn_FuelStatOpen.sqf
Additional configuration options to make life easier. Also, fixed when money should be taken from serviceChopper. You had the potential to accidentally lose $ I believe.
> Fuel Config Options

- BEFilters/scripts.txt
More stuff to add. Credits to Jawshy
> EDEN UPDATE

- BEFilters/scripts.txt
> EDEN UPDATE #2

- Altis_Life.Altis/Config_Vehicles.hpp
licenses[] = { {"CIV"}, {"COP"}, {"MEDIC"}, {"EAST"} };
> Added Documentation for Veh

- Altis_Life.Altis/core/fn_welcomeNotification.sqf
http://images.akamai.steamusercontent.com/ugc/318997942503676994/FB9DBAF35948A8150FC364A866A0C99C572D80BB/
Join the game and enjoy useful links. *Tested and should work fine*,
This addition should hopefully make it easier for server owners to enforce the need to sign up to the damn forum, apply for cop, donate and if they wish download workshop content *like my server*. Click the links for them to open up on a web browser.
> New Welcome Screen

- Altis_Life.Altis/core/functions/fn_keyHandler.sqf
Added animations for veh unlock / locking.
> Animations for Hunter / Other Veh

- Altis_Life.Altis/dialog/pInteraction.hpp
Small fix for vinteraction.
Same we do for pinteracton do get the same result.
> Editing the v/pInteraction menu for other languages

- AltisLife.sql
- Altis_Life.Altis/Config_Master.hpp
- Altis_Life.Altis/core/actions/fn_impoundAction.sqf
- Altis_Life.Altis/core/actions/fn_storeVehicle.sqf
Reverting this weird stuff while adding the damage save. its not needed
anymore. i can't reproduce any item save issues.
> Save damage to db (optional)

- AltisLife.sql
Fixing fuel vehicle in the DB.
> Error for create vehicle table

- Altis_Life.Altis/dialog/CustomPhone/Dialog/player_inv.hpp
- Altis_Life.Altis/stringtable.xml
Adding tooltip to phone for multilanguage support. Maybe deleting the
text on the Screen and just leave the icon there?
> Adding tooltip to phone

- life_server/init.sqf
for more information see issue #373
> removal of obsolete code in /life_server/init.sqf

- Altis_Life.Altis/dialog/vehicleShop.hpp
Changing the vehicleshop buttons and colorlist.
> Lets change the tiny buttons and colorlist

- Altis_Life.Altis/Config_Master.hpp
- life_hc/MySQL/General/fn_cleanup.sqf
- life_hc/MySQL/General/fn_insertVehicle.sqf
- life_hc/MySQL/Vehicles/fn_spawnVehicle.sqf
- life_hc/MySQL/Vehicles/fn_vehicleStore.sqf
- life_hc/MySQL/Vehicles/fn_vehicleUpdate.sqf
- life_server/Functions/Systems/fn_vehicleStore.sqf
- life_server/Functions/Systems/fn_vehicleUpdate.sqf
Please confirm its working before merging so we don't spam the github.
Rearranged the checks so it doesn't exit in the wrong order.
Rewrote the _trunk bit
Changed default item array.
Corrected my mistake in the update query when impounding vehicles -.-
Added the updates to headless client aswell.
> i swear it's a lack of sleep

- Altis_Life.Altis/mission.sqm
Fixed the "Error loading mission" bug when converting the mission in the
new 3D Editor
> Fixed EDEN Bug

- Altis_Life.Altis/core/pmenu/fn_giveItem.sqf
- Altis_Life.Altis/core/pmenu/fn_p_updateMenu.sqf
- Altis_Life.Altis/dialog/CustomPhone/Dialog/player_inv.hpp
This should fix it not updating
> Fix for phone not updating

- Altis_Life.Altis/core/shops/fn_clothingMenu.sqf
Completed.
ACTUALLY doesn't teleport the player if clothing_noTP = true
> Clothing shop noTP option

- life_server/Functions/Systems/fn_whoDoneit
Here's a little script I done a long time ago for death logs using spdlog via extDB
Needs updating for extDB2
Also add the following line in to Altis_Life.Altis\initPlayerServer.sqf (Create if not already existing)
> Change Idea - Death Logs

- Altis_Life.Altis/stringtable.xml
Because no one collects Heroin and Coke straight of plants.
> Correct Terminology/slang

- Altis_Life.Altis/core/functions/fn_keyHandler.sqf
- Altis_Life.Altis/core/vehicle/fn_openInventory.sqf
- Altis_Life.Altis/stringtable.xml
A few things have been translated into italian language. 
Then the openInventory bug is fixed in a cleaner way,using the sleep command for delaying for a random amount of time the opening of the trunk dialog,this disallow the players to open the same inventory at the same time.
> Localization and OpenInventory

- Altis_Life.Altis/Functions.hpp
Sorry about that,i forgot to push this file.
> Mining percents (2) -- functions.hpp

- Altis_Life.Altis/Config_Master.hpp
- Altis_Life.Altis/core/admin/fn_adminMenu.sqf
- Altis_Life.Altis/core/admin/fn_admininfo.sqf
- Altis_Life.Altis/core/functions/network/fn_jumpFnc.sqf
- Altis_Life.Altis/dialog/admin_menu.hpp
Remade the admin menu. still kept close to original.
Added secondary attatchments, everything should be alligned!
Dirty hotfix for superjump, could maybe cause other kinds of abuse but
beats death.
-There is still an issue with the adminmarkers not being disabled
properly so button will stay green/on until fixed.
> Damn Jawshy's eye for detail -Clean

- Altis_Life.Altis/core/init.sqf
- Altis_Life.Altis/core/session/fn_insertPlayerInfo.sqf
- life_hc/MySQL/General/fn_insertRequest.sqf
- life_server/Functions/MySQL/fn_insertRequest.sqf
Not sure who would try to exploit between 3-7.5k by default... But I guess there is people who have nothing better to do.
This is just one option I came up with. Submitting another Option
> Bank Exploit Fix

- Altis_Life.Altis/CfgRemoteExec.hpp
- Altis_Life.Altis/Config_Master.hpp
- Altis_Life.Altis/Functions.hpp
- Altis_Life.Altis/core/actions/fn_seizePlayerAction.sqf
- Altis_Life.Altis/core/cop/fn_copInteractionMenu.sqf
- Altis_Life.Altis/core/cop/fn_seizeClient.sqf
- Altis_Life.Altis/dialog/pInteraction.hpp
- Altis_Life.Altis/stringtable.xml
Basically the seize script everyone uses since 3.1.4.8, just modified to work and some config options.
3.1.4.5 Skalicon Release:
http://www.altisliferpg.com/topic/5149-tutorial-seizeweapon-3145/
Similar stuff:
http://www.altisliferpg.com/topic/13621-update-seize-weapons-directly-from-player-for-44/
http://www.altisliferpg.com/topic/12229-3148-release-search-seize-for-cops/
> Seize Player Items

- Altis_Life.Altis/Config_Clothing.hpp
Added the Police Vest, Cap and Beret.
> More cop clothing

- Altis_Life.Altis/Config_Master.hpp
- Altis_Life.Altis/core/shops/fn_chopShopMenu.sqf
- Altis_Life.Altis/core/shops/fn_vehicleShopBuy.sqf
- Altis_Life.Altis/core/shops/fn_vehicleShopLBChange.sqf
- Altis_Life.Altis/dialog/function/fn_garageLBChange.sqf
- Altis_Life.Altis/dialog/function/fn_sellGarage.sqf
- Altis_Life.Altis/dialog/function/fn_unimpound.sqf
> Multiplicator -> Multiplier

- Altis_Life.Altis/Functions.hpp
Will it stay in alphabetical order? Probably not...
> Alphabetical Ordering of Functions.hpp

- Altis_Life.Altis/core/admin/fn_adminMenu.sqf
- Altis_Life.Altis/core/admin/fn_admingetID.sqf
- Altis_Life.Altis/core/session/fn_insertPlayerInfo.sqf
- Altis_Life.Altis/core/session/fn_updateRequest.sqf
- life_hc/MySQL/General/fn_updateRequest.sqf
- life_server/Functions/Gangs/fn_removeGang.sqf
- life_server/Functions/Housing/fn_addHouse.sqf
- life_server/Functions/MySQL/fn_insertRequest.sqf
- life_server/Functions/MySQL/fn_updateRequest.sqf
- life_server/Functions/Systems/fn_getID.sqf
Just some better descriptions I felt. I'll do more later on. Just got bored.
> Description Updates

- Altis_Life.Altis/core/cop/fn_copInteractionMenu.sqf
- Altis_Life.Altis/core/housing/fn_containerMenu.sqf
- Altis_Life.Altis/dialog/pInteraction.hpp
Apparently Button8 sort of was just chillin. Empty. With no one to love
it.
I'm pretty sure this is all that needed to be modified to make the switch. If anyone catches anything else please post it. Otherwise looks like we'll be making use of number 8.
> Button9 -> Button8

- Altis_Life.Altis/dialog/FuelStat.hpp
- Altis_Life.Altis/dialog/admin_menu.hpp
- Altis_Life.Altis/dialog/bank.hpp
- Altis_Life.Altis/dialog/cell_phone.hpp
- Altis_Life.Altis/dialog/chop_shop.hpp
- Altis_Life.Altis/dialog/clothing.hpp
- Altis_Life.Altis/dialog/common.hpp
- Altis_Life.Altis/dialog/compensate.hpp
- Altis_Life.Altis/dialog/deathScreen.hpp
- Altis_Life.Altis/dialog/federalReserve.hpp
- Altis_Life.Altis/dialog/function/fn_garageLBChange.sqf
- Altis_Life.Altis/dialog/function/fn_unimpound.sqf
- Altis_Life.Altis/dialog/gang.hpp
- Altis_Life.Altis/dialog/hud_stats.hpp
- Altis_Life.Altis/dialog/impound.hpp
- Altis_Life.Altis/dialog/key_chain.hpp
- Altis_Life.Altis/dialog/pInteraction.hpp
- Altis_Life.Altis/dialog/player_inv.hpp
- Altis_Life.Altis/dialog/progress.hpp
- Altis_Life.Altis/dialog/settings.hpp
- Altis_Life.Altis/dialog/shop_items.hpp
- Altis_Life.Altis/dialog/shops.hpp
- Altis_Life.Altis/dialog/spawnSelection.hpp
- Altis_Life.Altis/dialog/ticket.hpp
- Altis_Life.Altis/dialog/trunk.hpp
- Altis_Life.Altis/dialog/veh_shop.hpp
- Altis_Life.Altis/dialog/vehicleShop.hpp
- Altis_Life.Altis/dialog/wanted_list.hpp
All should be well this time!
Yes, I did this all by hand. No, I don't want to know how I could've
done it easier.
I only did spacing, open close bracket locations, and such right now.
I'll work on the text formats and ordering at a later date.
> Dialog inconsistency cleanup

- Altis_Life.Altis/mission.sqm
I'll update the NPCs next... give me a few.
> Eden Mission SQM - Update 1 of 2

- Altis_Life.Altis/mission.sqm
No players, only playable.
All NPC's on one group.
Renamed all Callsigns, so it will be easier to edit in the future.
Callsigns doesnt have any effect ingame and i dont know why.
> Total Cleanup of the Mission

- Altis_Life.Altis/mission.sqm
I have manually checked every single NPC and put them on the surface.
So no more looking into the ground when buying donuts at the gas station.
> Nu more sunken NPC's

- Altis_Life.Altis/description.ext
Fixed players spawning as Seagull
Fixed AI/NPC from taking up slots, only if AI is active in mission.sqm
> fixed player slots

- Altis_Life.Altis/description.ext
After build 1050848 was released, alot of the configurations was moved to the mission.sqm
> Not needed in server build 1050848

- Altis_Life.Altis/Config_Master.hpp
- Altis_Life.Altis/core/actions/fn_arrestAction.sqf
- Altis_Life.Altis/core/actions/fn_pickupItem.sqf
- Altis_Life.Altis/core/actions/fn_pickupMoney.sqf
- Altis_Life.Altis/core/civilian/fn_robReceive.sqf
- Altis_Life.Altis/core/gangs/fn_createGang.sqf
- Altis_Life.Altis/core/housing/fn_buyHouse.sqf
- Altis_Life.Altis/core/housing/fn_sellHouse.sqf
- Altis_Life.Altis/core/shops/fn_chopShopSell.sqf
- Altis_Life.Altis/core/shops/fn_vehicleShopBuy.sqf
- Altis_Life.Altis/dialog/function/fn_bankDeposit.sqf
- Altis_Life.Altis/dialog/function/fn_bankTransfer.sqf
- Altis_Life.Altis/dialog/function/fn_bankWithdraw.sqf
- Altis_Life.Altis/dialog/function/fn_gangDeposit.sqf
- Altis_Life.Altis/dialog/function/fn_gangWithdraw.sqf
- Altis_Life.Altis/dialog/function/fn_sellGarage.sqf
- BEFilters/publicVariable.txt
- life_server/init.sqf
It'll log your money & player stuff. You have to enable it via the config. Can use the BEFriendly mode for making the BE Logs easier to read. When its disabled it outputs more info for your RPT.
> Data Logging

- Altis_Life.Altis/Config_Spyglass.hpp
- Altis_Life.Altis/mission.sqm
Added 25 more civilian slots and a couple medic slots to kinda bump it up. Also changed Civ -> Civilian for beauty purposes.
> 100 Civilian Map Support

- Altis_Life.Altis/Config_Master.hpp
- Altis_Life.Altis/core/medical/fn_onPlayerKilled.sqf
A simple check to make sure that server-owners cant set the respawn_timer below 5 seconds.
> 5 second minimum respawn time.

- Altis_Life.Altis/core/medical/fn_onPlayerKilled.sqf
- Altis_Life.Altis/dialog/deathScreen.hpp
it looks much cleaner without the miliseconds and the dialog is now symetric/aligned.
> Removed the miliseconds and cleaned up the dialog

- Altis_Life.Altis/stringtable.xml
> Spanish Strings

- Altis_Life.Altis/core/functions/fn_actionKeyHandler.sqf
#570 Only alive animals could be gutted
> #570 Only alive animals could be gutted

- Altis_Life.Altis/Functions.hpp
- Altis_Life.Altis/core/functions/fn_getDamage.sqf
> #589 - Check vehicle damage

- Altis_Life.Altis/Config_Master.hpp
- Altis_Life.Altis/core/actions/fn_healHospital.sqf
- Altis_Life.Altis/mission.sqm
- Altis_Life.Altis/stringtable.xml
> Hospital Heal

- Altis_Life.Altis/Config_Weapons.hpp
> Removed MineDetector

- Altis_Life.Altis/stringtable.xml
Please can someone verify the translations
> Medical Marijuana String

- Altis_Life.Altis/core/actions/fn_gather.sqf
- Altis_Life.Altis/core/functions/fn_whereAmI.sqf
- Altis_Life.Altis/core/vehicle/fn_deviceMine.sqf
- Altis_Life.Altis/dialog/function/fn_spawnPointCfg.sqf
> for loop optimisation

- Altis_Life.Altis/Config_Master.hpp
- life_server/init.sqf
> #622 - civ_alive between restarts

- Altis_Life.Altis/core/housing/fn_PlayerInBuilding.sqf
- Altis_Life.Altis/core/housing/fn_placeContainer.sqf
- Altis_Life.Altis/core/items/fn_placestorage.sqf
- Altis_Life.Altis/stringtable.xml
- Fixes the remainder of #631 (can place containers outside).
- Adds more accuracy for checking whether a player is in a building.
- Stops crates being placed over the stairs.
- Stops crates from exploding and disappearing.
I need people to just check over/test this before it's merged.
> Placing Storage fixes

- Altis_Life.Altis/initServer.sqf
- life_server/Functions/Systems/fn_whoDoneit.sqf
For the sake of optimisation that will no doubt be done later on this.
> Switch -> if then {} (whoDoneit) @daniel

- Altis_Life.Altis/core/civilian/fn_civLoadout.sqf
- life_hc/MySQL/General/fn_huntingZone.sqf
- life_server/Functions/Systems/fn_huntingZone.sqf
- life_server/fix_headgear.sqf
https://community.bistudio.com/wiki/selectRandom
> Some optimisation

- Altis_Life.Altis/script_macros.hpp
- life_server/script_macros.hpp
Originally Dan and I had discussed leaving the macros in the hpp to
support people adding in stuff. However, to prevent issues with the
repo, they're going. You can easily re-add them/keep them to support
your silly macro fetish..
> Remove Macro Support Sections

- Altis_Life.Altis/SpyGlass/fn_initSpy.sqf
- Altis_Life.Altis/core/fsm/client.fsm
- Altis_Life.Altis/core/housing/fn_buyHouse.sqf
Should Resolve: 
https://github.com/ArmaLife/Framework/issues/675 (Must've been a copy paste miss when I put it in.)
https://github.com/ArmaLife/Framework/issues/673 (A MACRO re-add mistake. Figured the fsm could handle it, guess not. Lol.)
https://github.com/ArmaLife/Framework/issues/672 (Related to when Macros were removed, sorry.)
> Expression Error Fixes

- Altis_Life.Altis/core/actions/fn_pickupMoney.sqf
- Altis_Life.Altis/core/civilian/fn_robReceive.sqf
- Altis_Life.Altis/core/gangs/fn_createGang.sqf
- Altis_Life.Altis/core/housing/fn_buyHouse.sqf
- Altis_Life.Altis/core/housing/fn_sellHouse.sqf
- Altis_Life.Altis/core/shops/fn_chopShopSell.sqf
- Altis_Life.Altis/core/shops/fn_vehicleShopBuy.sqf
- Altis_Life.Altis/dialog/function/fn_bankDeposit.sqf
- Altis_Life.Altis/dialog/function/fn_bankTransfer.sqf
- Altis_Life.Altis/dialog/function/fn_bankWithdraw.sqf
- Altis_Life.Altis/dialog/function/fn_gangDeposit.sqf
- Altis_Life.Altis/dialog/function/fn_gangWithdraw.sqf
- Altis_Life.Altis/dialog/function/fn_sellGarage.sqf
- Preceded money variables with a dollar sign ($). 
- to → into 
- Fixed: transfered → transferred
> _logs: Minor changes

- Altis_Life.Altis/Config_vItems.hpp
- Added: Sell prices to virtual items that otherwise could not be sold.
> Config_vItems: Added more sellPrice

- Altis_Life.Altis/core/shops/fn_clothingFilter.sqf
- Altis_Life.Altis/core/shops/fn_clothingMenu.sqf
- Altis_Life.Altis/core/shops/fn_virt_menu.sqf
Check this before merging, very tired.
> Remove last of EQUAL

- life_hc/MySQL/WantedSystem/fn_wantedBounty.sqf
- life_server/Functions/WantedSystem/fn_wantedBounty.sqf
Was returning a multi-array and selecting the third index, even though it only has 1.
> Bounty Query Fix

- Altis_Life.Altis/dialog/vehicleShop.hpp
> vehicleShop: Tab → 4 spaces

- Altis_Life.Altis/Config_Process.hpp
It was like cringe worthy. I have no clue why this got merged like this or who taught this person to format but holy shit.
> Format Fix - CfgProcess

- life_hc/hc_macros.hpp
- life_hc/initHC.sqf
- life_server/init.sqf
- life_server/script_macros.hpp
This reverts commit 7c4a6ffb82155844b2c090a58f1196c4af4c72b4.
If anybody wants to argue this, talk to me on Gitter, or give more information as to why this has already been added.
- Close to 4.5 release.
- extDB3 is 2 days old with some posted issues already. I have no problem with using it, but no rushing and slamming it straight in.
Edit: The initial commit is also screwed.
> Revert "Extdb2 ---> Extdb3"

- Altis_Life.Altis/core/functions/fn_actionKeyHandler.sqf
- Altis_Life.Altis/core/functions/fn_handleDamage.sqf
Revive exploit fix : In Classname of Rabbit Man is used so iskindof Man
work with rabbit need to put another check don't use in animal
#498
> Don't taze dead + don't revive animals

- Altis_Life.Altis/Config_Master.hpp
- Altis_Life.Altis/core/items/fn_jerrycanRefuel.sqf
- Altis_Life.Altis/stringtable.xml
Uses a verification dialog. Checks for the money, and will remove,
cancels if you don't have it...
Yeah. Cool. I know right?
@Jawshy - Sorry for the additional strings...
> Fuel Can Updates

- Altis_Life.Altis/core/init.sqf
- life_server/init.sqf
This will help is identify which versions people are running when
requesting support by posting their RPT files. To see what version they
are running. As long as we update this :dancer:
> diag_log Versions

- Altis_Life.Altis/core/functions/fn_handleDamage.sqf
I wasn't able to test it.
@Jawshy 
@tkcjesse 
@Heavybob 
Can one of you test it?
> handleDamage: Clean

- Altis_Life.Altis/config/Config_SpawnPoints.hpp
Line 55 said class RebelS 
Which is really Northern Rebel, so i thought it should be RebelN for North...
Line 63 said class RebelN
Which is really Southern Rebel... So the same as above, but weird :p
RebelE is fine though :p
> Line 55 & Line 63 - Screwed

- Altis_Life.Altis/stringtable.xml
- Fix: Should fix `Unknown entity: ' lt'` and `Unknown entity: ' gt'` errors in the RPT file. 
- Should close #838. 
**Please test before merging.**
> Stringtable: Fix: Unknown entity (#838)

- Altis_Life.Altis/stringtable.xml
* Added all Data Logging & Init Spanish Strings.
* Added a few missing Spanish strings
* Updated some wrong translations
Sorry about all those pulls, last commit was a change to the stringtable and didnt notice until after I made the last pull.
Was just a "<" so just updated it manually.
> Spanish Strings 2

- Altis_Life.Altis/core/actions/fn_buyLicense.sqf
> Fixes ArmaLife/Framework#856

- .github/CONTRIBUTING.md
- **Issues** 
- Added: Guidelines on creating a good issue. 
- **Pull Requests** 
- Changed: Tried to improve the prose of one of the bullet points. 
- **Can I help?** 
- Changed: Re-worded first point. Added quick explanation of why being
competent in those would be helpful to improving the framework.
- Changed: Slight wording change.
- Added: Link to issues that need addressing.
> Contributing: Update: Issues, PRs, and Can I help?
