- Altis_Life.Altis/mission.sqm
Fixed cocaine and heroin variables in mission.sqm that prevented the gang hideouts' drug processor from correctly working. 
Originally submitted at TAWTonic/Altis-Life#429
> Fixed cocaine and heroin variables

- Altis_Life.Altis/Config_Vehicles.hpp
Purchase quad bike and sell at a chop shop for a profit. 
Would suggest that chopshop prices are defined by 50% of what the car is worth in the config.
I don't think insurance works either.
> Quadbike money exploit

- Altis_Life.Altis/core/actions/fn_catchTurtle.sqf
- Altis_Life.Altis/stringtable.xml
Caught turtles will now be added to the player's virtual inventory and their name will correctly display.
> Catch turtle and turtle name fix

- Altis_Life.Altis/core/civilian/fn_removeLicenses.sqf
"pilot" not "air" as per Config_Licenses.hpp
(via GitHub Desktop -- let's see if I did it right)
> Fixed pilot licence variable

- Altis_Life.Altis/mission.sqm
This will stop cops bodies from appearing at the airport before they
actually respawn.
> Cop: Moved respawn marker to spawn island (Was at airport)

- Altis_Life.Altis/core/functions/fn_playerTags.sqf
Fixes the WARNING: Function 'name' that spams to the RPT. Tested to verify you can still see NPC names/player tags on users. Not sure if this line would be better to add on the **core\init.sqf** to the stacked event handler? @danielstuart14 maybe you can find the more "performance optimized" solution.
Reason for this issue was because Bohemia made dead units go completely null...
@danielstuart14, you could potentially revert https://github.com/ArmaLife/Altis/commit/7ff46c2f3a5bf4fefdd904fb7deab6be32502983 if you want. It seems to have **completely** fixed the bodies staying around or names showing on dead bodies and stuff like that though..
> Warning Spam Fix numba 2

- Altis_Life.Altis/core/pmenu/fn_keyGive.sqf
Fix problem when give key if you don't select a vehicle or a player
Fix for issue : Error in expression - fn_keyGive.sqf #131
> Fix key give

- Altis_Life.Altis/core/functions/fn_keyHandler.sqf
Doesn't directly address: https://github.com/ArmaLife/Altis/issues/146
However, stops a lot of things people do whilst restrained.
> Prevent Movement in Restraints

- Altis_Life.Altis/core/configuration.sqf
- Altis_Life.Altis/core/medical/fn_onPlayerKilled.sqf
- Altis_Life.Altis/core/medical/fn_revived.sqf
So currently if you get revived you don't keep your primary since its fetching dead gear when your primary is already on the ground basically and no longer considered to be your primary and then it gets deleted before making it to the fetch. 
This method will now fetch your gear successfully and then when you get revived you keep your primary weapon.
> Fix Revive Gear

- Altis_Life.Altis/Config_Weapons.hpp
Fixes minors issues from 1f906e1 → Altis_Life.Altis/Config_Weapons.hpp
Changes:
- Should fix the "30Rnd_65x39_caseless_mag" for the "arifle_MXC_F" not
appearing in the "Magazine" menu in the cop_sergeant shop.
- Removed "30Rnd_9x21_Mag" in the rebel shop as it had no matching
weapon.
- Re-ordered items and mags.
> Weapon Shop: Magazine Menu: Minor fix

- Altis_Life.Altis/core/admin/fn_adminMarkers.sqf
Admin menu → Markers. Player markers are determined by their side/faction.
> fn_adminMarkers.sqf - player side determines marker colour

- Altis_Life.Altis/Config_Master.hpp
- Altis_Life.Altis/Config_Vehicles.hpp
- Altis_Life.Altis/core/cop/fn_copLights.sqf
- Altis_Life.Altis/core/cop/fn_sirenLights.sqf
- Altis_Life.Altis/core/functions/fn_keyHandler.sqf
- life_server/Functions/Systems/fn_spawnVehicle.sqf
- Speedboat Minigun now rentable-only. 
- Added Hatchback (Sport) for police. 
- Moved Hunter HMG to cop_car from cop_air. 
- Added life_coplevel 2 for Speedboat Minigun. 
- Removed Regular camo hunter. 
- Hunters are now fully black. 
- Moved Digi Green Hummingbird to rebels from civilians. 
- Moved Sheriff Hummingbird to civilians from police (which still have
ion/black). 
- Set vehicle chop shop prices at approximately half of their rental
price as per @Heavybob's suggestion [here](https://github.com/ArmaLife/Altis/commit/ab981a7d0146a573b3d2e0290626b68919ee6fdf). 
- Removed Fresnel black SUV from police. 
- Removed identical Fresnel black Offroad from police. 
- Added config for SDV. 
- Miscellaneous changes. 
- Added police lights to Hatchback (Sport), Hummingbird, and Ghosthawk.
> Updated police vehicles, misc

- Altis_Life.Altis/mission.sqm
- All occurrences of `vehicle=` not equal to `C_man_1` changed to
`C_man_1`.
- Correctly ordered civilian and medic slots into ascending order.
- Changed medic slots' descriptions.
> Mission: Civ and medic slots update

- Altis_Life.Altis/core/functions/fn_clearVehicleAmmo.sqf
- Altis_Life.Altis/mission.sqm
```
0:04:18 Suspending not allowed in this context
0:04:18 Error in expression <> 0)) OR (_trunk3 select 0) > 0) then {
sleep 1200; 
_query = format["UPDATE veh>
0:04:18   Error position: <sleep 1200; 
_query = format["UPDATE veh>
0:04:18   Error Generic error in expression
0:04:18 File life_server\Functions\Systems\fn_vehicleStore.sqf, line 123
0:04:37 Suspending not allowed in this context
0:04:37 Error in expression <> 0)) OR (_trunk3 select 0) > 0) then {
sleep 1200; 
_query = format["UPDATE veh>
0:04:37   Error position: <sleep 1200; 
_query = format["UPDATE veh>
0:04:37   Error Generic error in expression
0:04:37 File life_server\Functions\Systems\fn_vehicleStore.sqf, line 123
```
Could be wrong but im only having this problem with the default mission.sqm and why not remove those …
> Suspending not allowed

- Altis_Life.Altis/Config_Gather.hpp
- Altis_Life.Altis/core/actions/fn_gather.sqf
- Altis_Life.Altis/core/actions/fn_mine.sqf
1.  Mining percents easily configurable using config_gather
2. Mining and gather actions splitted again into different scripts
3. Two CfgClasses created (Resource and Minerals)
Everything is based on the requiredItem variable 
`+	if (_requiredItem == "pickaxe") exitWith { _exitforMine = true; };`
So if you need to add a resource that can be gathered using pickaxe,you'll be forced to put it in the Minerals block,even if it's not a mineral(But what else would you gather with a pickaxe?!)
Hope the features are clear. If you think something should be improved please post in the comments :)
> Mining Percents (Again)

- Altis_Life.Altis/core/shops/fn_vehicleShopInit3DPreview.sqf
Slows the rate at which the previewed vehicle spins.
Currently it spins fast enough to make me feel sick.
I don't know how you can possibly preview more than like one vehicle without going insane..
This is still pretty quick though in my opinion. If the background was black and not clouds it'd be easier on the eyes as well. May create a bounding box like what Exile did...
> Vehicle Preview Adjustments

- Altis_Life.Altis/core/medical/fn_onPlayerKilled.sqf
Will address - https://github.com/ArmaLife/Altis/issues/439
Should be fixed. Could've sworn this was in here at one point in time...
I know it's in respawned, however that's obviously not called till you respawn. Meh.
> Delete WeaponHolderSimulated on Death

- Altis_Life.Altis/Config_Master.hpp
- Altis_Life.Altis/core/fn_initMedic.sqf
- Altis_Life.Altis/core/functions/fn_onTakeItem.sqf
- Altis_Life.Altis/dialog/function/fn_garageLBChange.sqf
- Altis_Life.Altis/dialog/function/fn_unimpound.sqf
Few things here:
1. Moved/Renamed the allow_medic_weapons to accompany the new restrictions section
2. Moved paycheck interval to the paycheck settings area
3. Changed "vehicleGarage_StorFeeMultiplier" in Master_Config to be "vehicleGarage_StoreFeeMultiplier" (note the "e")
4. Added 2 options that essentially are the same, just for beautification and separation purposes. It will allow you to define easily what items you don't want civilians to be able to pickup or take from inventories.
This is not meant to be by any means an anti-hack/cheat replacement. Simply to more so work with the seize script as I found out you can't pickup cop clothes. Some servers like that. This will make it easier for owners to decide if they want people to pick up cop/medic clothes.
> TakeItem restrictions

- AltisLife.sql
Currently if people connect with names that have symbols or something not supported by the latin charset, their information won't save. utf-8 will solve those issues. Special characters and such should be limited via extdb or like BEC or something.. Not the database...
I've ran this for like roughly 3-4 months using utf8 general_ci and had no issues with 1,300+ entries. I did have issues with users using tags like § and what not. Their data wouldn't save and I'd have to have them change their name.
**Also changed "AltisLife" to "altislife", granted MySQL does this anyways... but yeah... only lowercase in names.**
> latin -> utf8

- Altis_Life.Altis/core/functions/fn_actionKeyHandler.sqf
it prefer to use the cursorObject, but with the copinteractionmenu it checks again with cursorTarget
And i changed the original _curTarget to _curObject.
`_curTarget = cursorObject;` was simply too sloppy.
> Fixed the escorting bug.

- Altis_Life.Altis/Config_vItems.hpp
- Altis_Life.Altis/core/civilian/fn_jail.sqf
- Set spikeStrip, lockpick, goldbar, blastingcharge, boltcutter, and defusekit as illegal items as they are either police-only, their uses are illegal, or acquiring them can only be done through illegal means. 
- Removed lockpick and boltcutter from the civilian market as they are now illegal items. As suggested by @tkcjesse. 
- Added toolkit to the med_market 
- Miscellaneous changes including to the formatting. 
- Added spikeStrip, lockpick, goldbar, blastingcharge, boltcutter, and defusekit to the array of virtual items to be removed from the virtual inventory of a player being jailed. 
**I will merge if no objections in the next few hours.**
> Virtual items: Update shops and attributes

- Altis_Life.Altis/core/actions/fn_escortAction.sqf
- Altis_Life.Altis/core/actions/fn_stopEscorting.sqf
- Altis_Life.Altis/core/cop/fn_copInteractionMenu.sqf
- Altis_Life.Altis/core/functions/fn_actionKeyHandler.sqf
- Altis_Life.Altis/core/medical/fn_onPlayerKilled.sqf
- Altis_Life.Altis/core/medical/fn_onPlayerRespawn.sqf
**Purpose:** To not use cursorTarget/Object on escorting to prevent the dialog from not popping up. This will now allow the menu to always show.
**NOTICE:** Tested the new menu and cop functions on the menu numerous times and various configurations...
**Changelog: **
_fn_escortAction.sqf_
-Added two new variables `escortingPlayer` & `isEscorting`
-Added a check to make it so the player can re-escort if something happens to the person being escorted. 
_fn_stopEscorting.sqf_
-Basically the above...  and added an emergency fall-back to cursorTarget that probably won't even work in the situations I could make up in my mind that this would ever be called. It was never called in any of my testing..
_fn_copInteractionMenu.sqf_
-Hides buttons on the menu to require that cops stop-escorting …
> ActionKeyHandler Revert/Fix

- Altis_Life.Altis/Config_Master.hpp
- Altis_Life.Altis/core/civilian/fn_jail.sqf
This will add Master_config options to specify VIRTUAL items they want removed from players when they are jailed. Also the ability to run our cop seize scripts on players when jailed, otherwise it will just remove guns/magazines like before...
@Jawshy thanks for the inspiration when I saw you editing that yesterday :+1:
> M_Config Jail Settings -> Virtual Items & Seize Script

- Altis_Life.Altis/core/functions/fn_playerSkins.sqf
@danielStuart14
You would get the follow error(HAVE TO LOAD AS COP): https://i.gyazo.com/3f300fc0b5333af1d24b93d95ff3a924.png
Removed the coplevel <= 7, since it shouldn't be above 7 due to SQL(enum) not allowing people to enter values higher than 7 unless the edit the field, in which they'd then have to edit this if we left a <= check anyways. 
So this way not only fixes the error, but will allow for players to simply add more uniforms and not have to edit this file, only their DB field.
Fixed the rpt erorr: https://i.gyazo.com/5e580ba49cd53e12840120c25657adf9.png
> Fix Cop Skins Error

- Altis_Life.Altis/Config_Master.hpp
- Altis_Life.Altis/Config_Vehicles.hpp
- Altis_Life.Altis/core/actions/fn_impoundAction.sqf
- Altis_Life.Altis/core/cop/fn_copInteractionMenu.sqf
- Altis_Life.Altis/core/housing/fn_sellHouse.sqf
- Altis_Life.Altis/core/shops/fn_chopShopMenu.sqf
- Altis_Life.Altis/core/shops/fn_chopShopSell.sqf
- Altis_Life.Altis/core/shops/fn_vehicleShopBuy.sqf
- Altis_Life.Altis/core/shops/fn_vehicleShopLBChange.sqf
- Altis_Life.Altis/core/vehicle/fn_vInteractionMenu.sqf
- Altis_Life.Altis/dialog/function/fn_garageLBChange.sqf
- Altis_Life.Altis/dialog/function/fn_sellGarage.sqf
- Altis_Life.Altis/dialog/function/fn_unimpound.sqf
- Altis_Life.Altis/mission.sqm
- Altis_Life.Altis/stringtable.xml
**Purpose:** Basically to fix potential issues regarding vehicle costs/impounds/chops/etc. Also, to add a large amount of new features and defines for specifics.
**Background Issue:** The prior system would take the vehicle costs from the array, so if you tried to chopShop a cop only vehicle such as the HMG, you wouldn't get any money.
**_Config_Master.hpp_**
-Added the ability to specify kindOf vehicles to chop, so you don't have to dig in the files for it
--Added ability to chop aircraft
-Added numerous vehicle configs that are faction specific
**--You now will be able to set buy prices and rental prices specific to the playerSide!**
**_Config_Vehicles.hpp_**
-rentalPrice array is now a single number and is simply "price". By default it is what civilians will pay to BUY a vehicle. …
> Vehicle System Settings

- altislife.sql
Noticed some veh exceed this amount and do not get saved into the db. 
B_Heli_Transport_03_unarmed_green_F
For safe measure, changed to 64 (Apex may have longer classnames than 32)
> Increased Char Size

- Altis_Life.Altis/Config_Master.hpp
- Altis_Life.Altis/stringtable.xml
- altislife.sql
- life_hc/MySQL/Vehicles/fn_spawnVehicle.sqf
- life_hc/MySQL/Vehicles/fn_vehicleStore.sqf
- life_server/Functions/Systems/fn_spawnVehicle.sqf
- life_server/Functions/Systems/fn_vehicleStore.sqf
Nice addition to the vehicle inventory saving system,basically it checks if a vehicle gets stored with illegal items in it,and if the check returns true,the illegal item gets saved and the police gets advised when and where the player gets back his 'illegal' vehicle. Could be simply enabled/disabled by the cfgmaster,requires the save_inventory(virtual) parameter set to true.
I'd really like someone to test it another time (I tested it,but i'd prefer someone else's confirmation)
Hope the feature gets appreciated!
> Vehicle Trunk Check + Localization

- Altis_Life.Altis/core/fn_initCiv.sqf
- Altis_Life.Altis/core/session/fn_updatePartial.sqf
- Altis_Life.Altis/core/session/fn_updateRequest.sqf
- life_server/Functions/Systems/fn_clientDisconnect.sqf
#541 This will set the players position on top of the nearest colliding (walkable) surface equal or below their elevation when they logged out (if their elevation is negative and they are on land, they spawn on the ground). I.e, if they logged out on a roof, they will spawn there. In the case they log on mid air (vehicle), they will spawn on the ground below it. If they were in the ocean (above or below), they will spawn on the surface. Had a fight with my laptop while setting up git again, ignore the spam of commits on the issue. Enjoy!
> #541 Fixes - Spawning in air

- Altis_Life.Altis/core/cop/fn_restrain.sqf
- Altis_Life.Altis/core/functions/fn_actionKeyHandler.sqf
Without the sleep in restrain, the player will not be moved back into the vehicle (happens too quickly).
Using ASLtoATL (getPosASL player) is the equivalent of using getPosATL, and even then using ATL in nearestObjects in this scenario is wrong. Using just the object player is absolutely fine.
> Fix the fixes

- Altis_Life.Altis/core/functions/fn_keyHandler.sqf
- Altis_Life.Altis/core/functions/network/fn_jumpFnc.sqf
The idea here was to run jumpFnc on firstly the player, then sync the animation with everyone else except the player (filtered using a parameter). Why don't we just remove the run parameter? This will execute the script on every client and filter the player by where it is local, achieving the same exact thing.
I don't see a problem with this unless someone can shed some light on it I haven't considered.
Edit* Tested this and it works (syncs just fine)
> jumpfnc - Un-needed spawn?

- Altis_Life.Altis/stringtable.xml
Partially addresses #542. 
Translations done via Google Translate. 
Changes: 
- Added remaining French string localisations (186). 
- Added empty Spanish localisation. 
- Added empty Italian localisations. 
- Corrected German localisation for STR_ISTR_defuseKit_NotNear. 
- Miscellaneous fixes (grammar). 
@NiiRoZz, could you please verify the accuracy of the new French strings.
> Stringtable: Finished French localisation, misc

- altislife.sql
Switch to utf8mb4, as it supports all the Unicode characters.
It is compatible with MySQL 5.5 and newer and shouldn't be a problem,
since TIMESTAMP already is only compatible with 5.5+.
> SQL: Enable full Unicode support. utf8 -> utf8mb4

- Altis_Life.Altis/CfgRemoteExec.hpp
**These changes have been tested and are working as intended.** 
- Added: `F(BIS_fnc_effectKilledAirDestruction,ANYONE)` 
- Added: `F(BIS_fnc_effectKilledSecondaries,ANYONE)` 
- Fixed: Casing for `BIS_fnc_execVM` 
See also [CfgRemoteExec#Notes](https://community.bistudio.com/wiki/CfgRemoteExec#Notes) on the Bohemia Interactive Community Wiki. 
Client/local and server RPT log messages for reference: 
```
Scripting function 'bis_fnc_effectkilledsecondarie...' is not allowed to be remotely executed 
Scripting function 'bis_fnc_effectkilledairdestruc...' is not allowed to be remotely executed 
```
> CfgRemoteExec: Whitelist BIS functions

- Altis_Life.Altis/core/actions/fn_repairTruck.sqf
- Added: `closeDialog 0;` 
- Closes the interaction menu to prevent the player from being able to unflip the vehicle during repair. 
Tested and working.
> fn_repairTruck: Added closeDialog 0;

- Altis_Life.Altis/core/housing/fn_sellHouse.sqf
Stop the autoclick in dialog time to sell the house.
In this code:
if ((time - life_action_delay) < 2) exitWith {hint localize "STR_NOTF_ActionDelay";}; // No glitch.
life_action_delay = time;
I grabbed base of fn_sellGarage.sqf
> Some optimization and stop autoclick - SellHouse

- Altis_Life.Altis/core/housing/fn_sellHouse.sqf
Reverts ArmaLife/Framework#727
Firstly, there is no proper issue relating to this, I'm still unsure what this is on about. If it's what I'm thinking, there is a better way of doing it, no to mention the string isn't localised. No more pulling random shit please.
> Revert "Some optimization and stop autoclick - SellHouse"

- Altis_Life.Altis/core/items/fn_storageBox.sqf
Credits to BoGuu. I brought up the issue to him. He had the fix already... just was too lazy to commit it. Apparently Overwatch is more important. Lol.
Prevents people from pulling out the storage box in the open world and trying to slay others with it...
> House Storage Check

- life_client/core/cop/fn_copMarkers.sqf
Resolves https://github.com/ArmaLife/Framework/issues/860. 
- Fix: For https://github.com/ArmaLife/Framework/issues/860 by @Raided. 
> Needs testing, should allow police to see death markers when 0 medics are online.
> fn_copMarkers: Fix: #860
